services:
  - type: web
    name: Ai-agent-app
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn -k uvicorn.workers.UvicornWorker backend.app:app
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false